"""
Presentation Generator Data Models

Defines all Pydantic models for the presentation generation service.
"""
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field
import uuid


class SlideType(str, Enum):
    """Types of slides in a presentation"""
    TITLE = "title"
    CONTENT = "content"
    CODE = "code"
    CODE_DEMO = "code_demo"
    DIAGRAM = "diagram"
    SPLIT = "split"
    TERMINAL = "terminal"
    CONCLUSION = "conclusion"


class PresentationStyle(str, Enum):
    """Visual styles/themes for presentations"""
    DARK = "dark"
    LIGHT = "light"
    GRADIENT = "gradient"
    OCEAN = "ocean"


class PresentationStage(str, Enum):
    """Stages of presentation generation pipeline"""
    QUEUED = "queued"
    PLANNING = "planning"
    GENERATING_SLIDES = "generating_slides"
    EXECUTING_CODE = "executing_code"  # Phase 2: Execute code demos
    CREATING_ANIMATIONS = "creating_animations"  # Phase 2: Create typing animations
    GENERATING_VOICEOVER = "generating_voiceover"
    GENERATING_AVATAR = "generating_avatar"  # Phase 2: Generate avatar video
    COMPOSING_VIDEO = "composing_video"
    COMPLETED = "completed"
    FAILED = "failed"


class CodeBlock(BaseModel):
    """A code block within a slide"""
    language: str = Field(..., description="Programming language")
    code: str = Field(..., description="The code content")
    filename: Optional[str] = Field(None, description="Optional filename to display")
    highlight_lines: List[int] = Field(default_factory=list, description="Lines to highlight")
    execution_order: int = Field(default=0, description="Order for execution in demos")
    expected_output: Optional[str] = Field(None, description="Expected output for validation")
    show_line_numbers: bool = Field(default=True, description="Show line numbers")


class Slide(BaseModel):
    """A single slide in the presentation"""
    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    type: SlideType = Field(..., description="Type of slide")
    title: Optional[str] = Field(None, description="Slide title")
    subtitle: Optional[str] = Field(None, description="Optional subtitle")
    content: Optional[str] = Field(None, description="Text content (markdown supported)")
    bullet_points: List[str] = Field(default_factory=list, description="Bullet points")
    code_blocks: List[CodeBlock] = Field(default_factory=list, description="Code blocks")
    duration: float = Field(default=10.0, description="Duration in seconds")
    voiceover_text: str = Field(default="", description="Text for voiceover narration")
    transition: str = Field(default="fade", description="Transition effect")
    notes: Optional[str] = Field(None, description="Speaker notes")
    image_url: Optional[str] = Field(None, description="Generated slide image URL")
    diagram_type: Optional[str] = Field(None, description="Type of diagram: flowchart, architecture, process, comparison, hierarchy")
    job_id: Optional[str] = Field(None, description="Job ID for file naming")
    index: int = Field(default=0, description="Slide index in presentation")


class PresentationScript(BaseModel):
    """Complete presentation script generated by GPT-4"""
    title: str = Field(..., description="Presentation title")
    description: str = Field(..., description="Brief description")
    target_audience: str = Field(default="developers", description="Target audience")
    target_career: Optional[str] = Field(default=None, description="Target career for diagram focus (e.g., 'data_engineer', 'cloud_architect')")
    language: str = Field(..., description="Primary programming language")
    total_duration: int = Field(..., description="Total duration in seconds")
    slides: List[Slide] = Field(..., description="List of slides")
    code_context: Dict[str, Any] = Field(default_factory=dict, description="Shared code context")
    rag_verification: Optional[Dict[str, Any]] = Field(default=None, description="RAG usage verification metrics")

    @property
    def slide_count(self) -> int:
        return len(self.slides)

    @property
    def code_slide_count(self) -> int:
        return len([s for s in self.slides if s.type in [SlideType.CODE, SlideType.CODE_DEMO]])


class TitleStyle(str, Enum):
    """Title style for slide generation - affects how titles sound"""
    CORPORATE = "corporate"      # Professional, formal for enterprise training
    ENGAGING = "engaging"        # Dynamic, attention-grabbing for content creators
    EXPERT = "expert"            # Technical precision for advanced audiences
    MENTOR = "mentor"            # Warm, educational for learning platforms
    STORYTELLER = "storyteller"  # Narrative-driven for tutorials
    DIRECT = "direct"            # Clear, concise for documentation


class TypingSpeed(str, Enum):
    """Typing animation speed presets"""
    SLOW = "slow"          # ~2 chars/sec - very deliberate, teaching pace
    NATURAL = "natural"    # ~4 chars/sec - human explaining while typing (default)
    MODERATE = "moderate"  # ~6 chars/sec - confident developer
    FAST = "fast"          # ~10 chars/sec - experienced coder


class GeneratePresentationRequest(BaseModel):
    """Request to generate a new presentation"""
    topic: str = Field(..., description="Topic/prompt for the presentation", min_length=10)
    language: str = Field(default="python", description="Primary programming language")
    content_language: str = Field(default="en", description="Language for content (voiceover, titles, text). Examples: 'en', 'fr', 'es', 'de'")
    duration: int = Field(default=300, description="Target duration in seconds (60-900)", ge=60, le=900)
    style: PresentationStyle = Field(default=PresentationStyle.DARK, description="Visual style")
    include_avatar: bool = Field(default=False, description="Include avatar presenter")
    avatar_id: Optional[str] = Field(None, description="Avatar ID if include_avatar is True")
    voice_id: Optional[str] = Field(default="alloy", description="Voice ID for narration")
    execute_code: bool = Field(default=False, description="Execute code demos (Phase 2)")
    show_typing_animation: bool = Field(default=False, description="Show typing animation (Phase 2)")
    typing_speed: TypingSpeed = Field(default=TypingSpeed.NATURAL, description="Typing animation speed: slow, natural, moderate, fast")
    target_audience: str = Field(default="intermediate developers", description="Target audience")
    target_career: Optional[str] = Field(default=None, description="Target career for diagram focus (e.g., 'data_engineer', 'cloud_architect'). See TechCareer enum for full list.")
    title_style: Optional[TitleStyle] = Field(default=TitleStyle.ENGAGING, description="Title style for slides: corporate, engaging, expert, mentor, storyteller, direct")
    # RAG Support - documents uploaded via course-generator
    document_ids: List[str] = Field(default_factory=list, description="IDs of uploaded documents to use as source material (from course-generator)")
    rag_context: Optional[str] = Field(None, description="Pre-fetched RAG context (set by server after querying documents)")
    use_documents_for_diagrams: bool = Field(default=True, description="Extract and use diagrams/schemas from source documents")

    class Config:
        json_schema_extra = {
            "example": {
                "topic": "Introduction to Python decorators with practical examples",
                "language": "python",
                "content_language": "en",
                "duration": 300,
                "style": "dark",
                "include_avatar": False,
                "voice_id": "alloy",
                "execute_code": False,
                "show_typing_animation": False,
                "typing_speed": "natural",
                "target_audience": "intermediate Python developers",
                "target_career": "backend_developer",
                "title_style": "engaging"
            }
        }


class PresentationJob(BaseModel):
    """Tracks the status of a presentation generation job"""
    job_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    status: str = Field(default="queued", description="Current status")
    current_stage: PresentationStage = Field(default=PresentationStage.QUEUED)
    progress: float = Field(default=0.0, description="Progress percentage 0-100")
    message: str = Field(default="", description="Current status message")

    # Request parameters
    request: Optional[GeneratePresentationRequest] = None

    # Generated content
    script: Optional[PresentationScript] = None
    slide_images: List[str] = Field(default_factory=list, description="URLs of generated slide images")
    code_execution_results: Dict[str, Any] = Field(default_factory=dict, description="Code execution results by slide ID")
    animation_videos: List[str] = Field(default_factory=list, description="URLs of typing animation videos")
    voiceover_url: Optional[str] = Field(None, description="URL of generated voiceover audio")
    avatar_video_url: Optional[str] = Field(None, description="URL of avatar video (if enabled)")
    output_url: Optional[str] = Field(None, description="Final video URL")

    # Timestamps
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = None

    # Error handling
    error: Optional[str] = None
    error_details: Optional[Dict[str, Any]] = None

    def update_progress(self, stage: PresentationStage, progress: float, message: str = ""):
        """Update job progress"""
        self.current_stage = stage
        self.progress = progress
        self.message = message
        self.updated_at = datetime.utcnow()

        if stage == PresentationStage.COMPLETED:
            self.status = "completed"
            self.completed_at = datetime.utcnow()
        elif stage == PresentationStage.FAILED:
            self.status = "failed"
        else:
            self.status = "processing"


class SlidePreviewRequest(BaseModel):
    """Request to preview a single slide"""
    slide: Slide = Field(..., description="Slide to preview")
    style: PresentationStyle = Field(default=PresentationStyle.DARK)


class SlidePreviewResponse(BaseModel):
    """Response with slide preview"""
    image_url: str = Field(..., description="URL of the generated preview image")
    width: int = Field(default=1920)
    height: int = Field(default=1080)


class LanguageInfo(BaseModel):
    """Information about a supported programming language"""
    id: str
    name: str
    file_extension: str
    supported: bool
    icon: str


class StyleInfo(BaseModel):
    """Information about a presentation style"""
    id: str
    name: str
    preview_colors: Dict[str, str]
