openapi: 3.0.3
info:
  title: Visual Generator API
  description: |
    Professional diagram and visualization generation microservice.

    Isolated service with heavy dependencies (Graphviz, Matplotlib, etc.)
    for generating high-quality diagrams for educational content.

    ## Renderers
    - **Python Diagrams**: AWS, Azure, GCP, Kubernetes architecture icons
    - **Mermaid**: Flowcharts, sequences, mindmaps (via Kroki)
    - **Matplotlib**: Data charts (line, bar, scatter, etc.)

    ## Target Audiences
    Diagram complexity adapts to audience:
    - **Beginner**: 5-7 nodes, high-level concepts
    - **Senior**: 10-15 nodes, detailed protocols, clusters
    - **Executive**: 6-8 nodes, value flow, minimal tech jargon
  version: 1.0.0

servers:
  - url: http://localhost:8003
    description: Development server

tags:
  - name: Health
    description: Health and info endpoints
  - name: Diagrams
    description: Diagram generation
  - name: Mermaid
    description: Mermaid diagram rendering
  - name: Detection
    description: Diagram need detection
  - name: Management
    description: Diagram file management

paths:
  /health:
    get:
      tags: [Health]
      summary: Health check
      responses:
        '200':
          description: Service healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  service:
                    type: string
                    example: visual-generator
                  version:
                    type: string
                    example: 1.0.0
                  openai_configured:
                    type: boolean

  /info:
    get:
      tags: [Health]
      summary: Service information
      description: Get supported renderers, diagram types, styles, and formats
      responses:
        '200':
          description: Service info
          content:
            application/json:
              schema:
                type: object
                properties:
                  service:
                    type: string
                  description:
                    type: string
                  renderers:
                    type: array
                    items:
                      type: string
                  supported_types:
                    type: array
                    items:
                      type: string
                  supported_styles:
                    type: array
                    items:
                      type: string
                  supported_formats:
                    type: array
                    items:
                      type: string
                  providers:
                    type: array
                    items:
                      type: string

  /api/v1/diagrams/generate:
    post:
      tags: [Diagrams]
      summary: Generate diagram from description
      description: |
        Generate a professional diagram from natural language description.

        Uses the Python Diagrams library for architecture diagrams,
        with official icons from AWS, Azure, GCP, Kubernetes, etc.

        ## Diagram Types
        - architecture, flowchart, sequence, class, state
        - hierarchy, process, comparison, mindmap
        - line_chart, bar_chart, scatter, histogram

        ## Providers
        - aws, azure, gcp, k8s, onprem, generic
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DiagramGenerateRequest'
      responses:
        '200':
          description: Diagram generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiagramGenerateResponse'
        '503':
          description: OpenAI API key not configured

  /api/v1/diagrams/mermaid:
    post:
      tags: [Mermaid]
      summary: Render Mermaid diagram
      description: |
        Render a Mermaid diagram from code.
        Uses Kroki self-hosted API (primary) or mermaid.ink (fallback).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MermaidRenderRequest'
      responses:
        '200':
          description: Diagram rendered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiagramGenerateResponse'

  /api/v1/diagrams/detect:
    post:
      tags: [Detection]
      summary: Detect diagram need
      description: Analyze content to determine if a diagram would be helpful
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DetectDiagramRequest'
      responses:
        '200':
          description: Detection result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetectionResult'

  /api/v1/diagrams/{filename}:
    get:
      tags: [Management]
      summary: Get generated diagram
      description: Retrieve a generated diagram by filename
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
          example: diagram_abc123.png
      responses:
        '200':
          description: Diagram file
          content:
            image/png:
              schema:
                type: string
                format: binary
            image/svg+xml:
              schema:
                type: string
                format: binary
        '404':
          description: Diagram not found

    delete:
      tags: [Management]
      summary: Delete diagram
      description: Delete a generated diagram file
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Diagram deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  deleted:
                    type: string
        '404':
          description: Diagram not found

  /api/v1/diagrams/cleanup:
    post:
      tags: [Management]
      summary: Cleanup old diagrams
      description: Delete diagrams older than specified hours
      parameters:
        - name: max_age_hours
          in: query
          schema:
            type: integer
            default: 24
      responses:
        '200':
          description: Cleanup complete
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  deleted_count:
                    type: integer

components:
  schemas:
    DiagramType:
      type: string
      enum:
        # Mermaid types
        - flowchart
        - sequence
        - class
        - state
        - er
        - gantt
        - pie
        - mindmap
        - timeline
        - architecture
        - hierarchy
        - process
        - comparison
        # Matplotlib types
        - line_chart
        - bar_chart
        - scatter
        - histogram
        - heatmap
        - box_plot
        # Manim types
        - animation
        - math
        - graph
        - transform
        - code_viz
        - data_structure
        - algorithm

    DiagramStyle:
      type: string
      enum: [dark, light, neutral, colorful, minimal, corporate]

    RenderFormat:
      type: string
      enum: [png, svg, mp4, gif, webm]

    TargetAudience:
      type: string
      enum: [beginner, senior, executive]
      description: |
        Audience level for diagram complexity adjustment:
        - beginner: Simple, few nodes, high-level concepts
        - senior: Detailed, specific protocols, clusters
        - executive: Value flow, system boundaries, minimal tech details

    RenderingEngine:
      type: string
      enum: [diagrams_python, mermaid, matplotlib]

    DiagramGenerateRequest:
      type: object
      required: [description]
      properties:
        description:
          type: string
          description: Natural language description of the diagram
        diagram_type:
          $ref: '#/components/schemas/DiagramType'
        style:
          $ref: '#/components/schemas/DiagramStyle'
        provider:
          type: string
          description: Cloud provider (aws, azure, gcp, k8s, onprem)
        title:
          type: string
        context:
          type: string
          description: Additional context for better generation
        language:
          type: string
          default: en
        format:
          $ref: '#/components/schemas/RenderFormat'
        audience:
          $ref: '#/components/schemas/TargetAudience'
        engine:
          $ref: '#/components/schemas/RenderingEngine'
        cheat_sheet:
          type: string
          description: Valid imports cheat sheet for LLM

    DiagramGenerateResponse:
      type: object
      properties:
        success:
          type: boolean
        diagram_type:
          $ref: '#/components/schemas/DiagramType'
        file_path:
          type: string
        file_url:
          type: string
        generation_time_ms:
          type: integer
        renderer_used:
          type: string
        error:
          type: string

    MermaidRenderRequest:
      type: object
      required: [code]
      properties:
        code:
          type: string
          description: Mermaid diagram code
          example: |
            graph TD
                A[Producer] --> B[Kafka Broker]
                B --> C[Consumer]
        diagram_type:
          $ref: '#/components/schemas/DiagramType'
        title:
          type: string
        theme:
          type: string
          default: dark
        format:
          $ref: '#/components/schemas/RenderFormat'

    DetectDiagramRequest:
      type: object
      required: [content]
      properties:
        content:
          type: string
          description: Content to analyze
        context:
          type: string

    DetectionResult:
      type: object
      properties:
        needs_diagram:
          type: boolean
        confidence:
          type: number
          minimum: 0
          maximum: 1
        suggested_type:
          $ref: '#/components/schemas/DiagramType'
        suggested_description:
          type: string
        reasoning:
          type: string
        additional_suggestions:
          type: array
          items:
            type: object

    NodeCoordinate:
      type: object
      description: Coordinates of a node (for camera animations)
      properties:
        name:
          type: string
        label:
          type: string
        x:
          type: number
        y:
          type: number
        width:
          type: number
        height:
          type: number
        bbox:
          type: array
          items:
            type: number
        center_x:
          type: number
        center_y:
          type: number

    DiagramCoordinates:
      type: object
      description: Complete coordinate data for camera animations
      properties:
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/NodeCoordinate'
        edges:
          type: array
          items:
            type: object
        graph_bbox:
          type: array
          items:
            type: number
        graph_width:
          type: number
        graph_height:
          type: number
        dpi:
          type: integer
          default: 96
